-- Tagquest default layout — single-template HUD redesign.
--
-- Archives any existing active tagquest system layout(s) and inserts a new
-- active row with the new layout JSON. The playground manifest-sync picks
-- up the new row by its higher remote_version.
--
-- Mirrors the canonical TS source at:
--   studio-taghunter/src/scenarios/bodies/tagquest/defaultLayout.ts
-- Keep them in sync if you edit either.

START TRANSACTION;

UPDATE layouts
   SET status = 'archived',
       updated_at = CURRENT_TIMESTAMP
 WHERE game_type = 'tagquest'
   AND owner_type = 'system'
   AND status = 'active';

INSERT INTO layouts (
    layout_data,
    game_type,
    scenario_uniqid,
    status,
    version,
    owner_type,
    owner_id,
    created_by_email,
    created_at,
    updated_at
) VALUES (
    JSON_OBJECT(
        'version', '3.0',
        'background', '@background',
        'elements', JSON_ARRAY(
            JSON_OBJECT('id', 'tagquest_template', 'type', 'image', 'name', 'Tagquest Template (overlay)',
                'filename', '@template', 'x', 0, 'y', 0, 'width', 100, 'height', 100),
            JSON_OBJECT('id', 'animation_quest_image', 'type', 'image', 'name', 'Quest Pieces Grid',
                'x', 28, 'y', 18, 'width', 44, 'height', 60,
                'fontSize', 8, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'animation_quest_name', 'type', 'text', 'name', 'Active Quest Name', 'previewText', 'Quest 1',
                'x', 32, 'y', 78.5, 'width', 40, 'height', 4,
                'fontSize', 18, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'timer', 'type', 'text', 'name', 'Timer', 'previewText', '00:00:00',
                'x', 1.5, 'y', 2.5, 'width', 22, 'height', 8,
                'fontSize', 55, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'team_name_text', 'type', 'text', 'name', 'Team Name', 'previewText', 'TEAM 1',
                'x', 27, 'y', 1.5, 'width', 44, 'height', 6,
                'fontSize', 70, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'score_label', 'type', 'text', 'name', 'Score Label', 'previewText', 'SCORE',
                'x', 79, 'y', 1.2, 'width', 17, 'height', 3,
                'fontSize', 12, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'score', 'type', 'text', 'name', 'Score', 'previewText', '0',
                'x', 84, 'y', 7, 'width', 14, 'height', 6,
                'fontSize', 60, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'malus_label', 'type', 'text', 'name', 'Malus Label', 'previewText', 'MALUS',
                'x', 4, 'y', 25.3, 'width', 16, 'height', 3,
                'fontSize', 12, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'malus_icon', 'type', 'image', 'name', 'Malus Icon', 'filename', '@malus_image',
                'x', 1.5, 'y', 19, 'width', 6, 'height', 8),
            JSON_OBJECT('id', 'malus_multiplicator', 'type', 'text', 'name', 'Malus Multiplicator', 'previewText', 'x0',
                'x', 9, 'y', 19, 'width', 6, 'height', 8,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'malus_points', 'type', 'text', 'name', 'Malus Points', 'previewText', '0',
                'x', 16, 'y', 19, 'width', 6, 'height', 8,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'late_malus_label', 'type', 'text', 'name', 'Late Malus Label', 'previewText', 'LATE MALUS',
                'x', 4, 'y', 50.1, 'width', 16, 'height', 3,
                'fontSize', 12, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'late_malus_icon', 'type', 'image', 'name', 'Late Malus Icon', 'filename', '@late_malus_image',
                'x', 1.5, 'y', 39, 'width', 6, 'height', 8),
            JSON_OBJECT('id', 'late_malus_multiplicator', 'type', 'text', 'name', 'Late Malus Multiplicator', 'previewText', 'x0',
                'x', 9, 'y', 39, 'width', 6, 'height', 8,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'late_malus_points', 'type', 'text', 'name', 'Late Malus Points', 'previewText', '0',
                'x', 16, 'y', 39, 'width', 6, 'height', 8,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'combo_points_label', 'type', 'text', 'name', 'Combo Points Label', 'previewText', 'COMBO POINTS',
                'x', 2, 'y', 74, 'width', 22, 'height', 3,
                'fontSize', 12, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'combo_6_title', 'type', 'text', 'name', 'Combo 6 Title', 'previewText', 'COMBO 6',
                'x', 2, 'y', 60, 'width', 9, 'height', 4,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'combo_6_multiplicator', 'type', 'text', 'name', 'Combo 6 Multiplicator', 'previewText', 'x0',
                'x', 2, 'y', 70, 'width', 9, 'height', 7,
                'fontSize', 55, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'combo_6_points', 'type', 'text', 'name', 'Combo 6 Points', 'previewText', '0',
                'x', 2, 'y', 82, 'width', 9, 'height', 7,
                'fontSize', 55, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'combo_4_title', 'type', 'text', 'name', 'Combo 4 Title', 'previewText', 'COMBO 4',
                'x', 12, 'y', 60, 'width', 9, 'height', 4,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'combo_4_multiplicator', 'type', 'text', 'name', 'Combo 4 Multiplicator', 'previewText', 'x0',
                'x', 12, 'y', 70, 'width', 9, 'height', 7,
                'fontSize', 55, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'combo_4_points', 'type', 'text', 'name', 'Combo 4 Points', 'previewText', '0',
                'x', 12, 'y', 82, 'width', 9, 'height', 7,
                'fontSize', 55, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'combo_2_title', 'type', 'text', 'name', 'Combo 2 Title', 'previewText', 'COMBO 2',
                'x', 22, 'y', 60, 'width', 9, 'height', 4,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'combo_2_multiplicator', 'type', 'text', 'name', 'Combo 2 Multiplicator', 'previewText', 'x0',
                'x', 22, 'y', 70, 'width', 9, 'height', 7,
                'fontSize', 55, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'combo_2_points', 'type', 'text', 'name', 'Combo 2 Points', 'previewText', '0',
                'x', 22, 'y', 82, 'width', 9, 'height', 7,
                'fontSize', 55, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            -- Quest row 1
            JSON_OBJECT('id', 'quest_1_name', 'type', 'text', 'name', 'Quest 1 Name', 'previewText', 'Quest 1',
                'x', 79, 'y', 13, 'width', 21, 'height', 2.8,
                'fontSize', 11, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'quest_1_icon', 'type', 'image', 'name', 'Quest 1 Icon', 'filename', '@quest_main_image_1',
                'x', 82, 'y', 16, 'width', 5, 'height', 10),
            JSON_OBJECT('id', 'quest_1_multiplicator', 'type', 'text', 'name', 'Quest 1 Multiplicator', 'previewText', 'x0',
                'x', 88, 'y', 16, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'quest_1_points', 'type', 'text', 'name', 'Quest 1 Points', 'previewText', '0',
                'x', 94, 'y', 16, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            -- Quest row 2
            JSON_OBJECT('id', 'quest_2_name', 'type', 'text', 'name', 'Quest 2 Name', 'previewText', 'Quest 2',
                'x', 79, 'y', 27.1, 'width', 21, 'height', 2.8,
                'fontSize', 11, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'quest_2_icon', 'type', 'image', 'name', 'Quest 2 Icon', 'filename', '@quest_main_image_2',
                'x', 82, 'y', 30.1, 'width', 5, 'height', 10),
            JSON_OBJECT('id', 'quest_2_multiplicator', 'type', 'text', 'name', 'Quest 2 Multiplicator', 'previewText', 'x0',
                'x', 88, 'y', 30.1, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'quest_2_points', 'type', 'text', 'name', 'Quest 2 Points', 'previewText', '0',
                'x', 94, 'y', 30.1, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            -- Quest row 3
            JSON_OBJECT('id', 'quest_3_name', 'type', 'text', 'name', 'Quest 3 Name', 'previewText', 'Quest 3',
                'x', 79, 'y', 41.2, 'width', 21, 'height', 2.8,
                'fontSize', 11, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'quest_3_icon', 'type', 'image', 'name', 'Quest 3 Icon', 'filename', '@quest_main_image_3',
                'x', 82, 'y', 44.2, 'width', 5, 'height', 10),
            JSON_OBJECT('id', 'quest_3_multiplicator', 'type', 'text', 'name', 'Quest 3 Multiplicator', 'previewText', 'x0',
                'x', 88, 'y', 44.2, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'quest_3_points', 'type', 'text', 'name', 'Quest 3 Points', 'previewText', '0',
                'x', 94, 'y', 44.2, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            -- Quest row 4
            JSON_OBJECT('id', 'quest_4_name', 'type', 'text', 'name', 'Quest 4 Name', 'previewText', 'Quest 4',
                'x', 79, 'y', 55.3, 'width', 21, 'height', 2.8,
                'fontSize', 11, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'quest_4_icon', 'type', 'image', 'name', 'Quest 4 Icon', 'filename', '@quest_main_image_4',
                'x', 82, 'y', 58.3, 'width', 5, 'height', 10),
            JSON_OBJECT('id', 'quest_4_multiplicator', 'type', 'text', 'name', 'Quest 4 Multiplicator', 'previewText', 'x0',
                'x', 88, 'y', 58.3, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'quest_4_points', 'type', 'text', 'name', 'Quest 4 Points', 'previewText', '0',
                'x', 94, 'y', 58.3, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            -- Quest row 5
            JSON_OBJECT('id', 'quest_5_name', 'type', 'text', 'name', 'Quest 5 Name', 'previewText', 'Quest 5',
                'x', 79, 'y', 69.4, 'width', 21, 'height', 2.8,
                'fontSize', 11, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'quest_5_icon', 'type', 'image', 'name', 'Quest 5 Icon', 'filename', '@quest_main_image_5',
                'x', 82, 'y', 72.4, 'width', 5, 'height', 10),
            JSON_OBJECT('id', 'quest_5_multiplicator', 'type', 'text', 'name', 'Quest 5 Multiplicator', 'previewText', 'x0',
                'x', 88, 'y', 72.4, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'quest_5_points', 'type', 'text', 'name', 'Quest 5 Points', 'previewText', '0',
                'x', 94, 'y', 72.4, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            -- Quest row 6
            JSON_OBJECT('id', 'quest_6_name', 'type', 'text', 'name', 'Quest 6 Name', 'previewText', 'Quest 6',
                'x', 79, 'y', 83.5, 'width', 21, 'height', 2.8,
                'fontSize', 11, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#000000ff'),
            JSON_OBJECT('id', 'quest_6_icon', 'type', 'image', 'name', 'Quest 6 Icon', 'filename', '@quest_main_image_6',
                'x', 82, 'y', 86.5, 'width', 5, 'height', 10),
            JSON_OBJECT('id', 'quest_6_multiplicator', 'type', 'text', 'name', 'Quest 6 Multiplicator', 'previewText', 'x0',
                'x', 88, 'y', 86.5, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff'),
            JSON_OBJECT('id', 'quest_6_points', 'type', 'text', 'name', 'Quest 6 Points', 'previewText', '0',
                'x', 94, 'y', 86.5, 'width', 5, 'height', 10,
                'fontSize', 50, 'fontFamily', 'Arial Black, Arial, sans-serif', 'color', '#ffffff')
        )
    ),
    'tagquest',
    NULL,
    'active',
    '3.0',
    'system',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

COMMIT;
